namespace Model.Configuration.Seed;

/// <summary>
/// Entity seed
/// </summary>
internal sealed class LanguageSeed : IEntityTypeConfiguration<Language>
{
    internal LanguageSeed()
    {
    }

    public void Configure(EntityTypeBuilder<Language> builder) =>
        _ = builder.HasData(
            new Language(1, "Afrikaans"),
            new Language(2, "Albanian"),
            new Language(3, "Amharic"),
            new Language(4, "Arabic"),
            new Language(5, "Armenian"),
            new Language(6, "Azerbaijani"),
            new Language(7, "Basque"),
            new Language(8, "Belarusian"),
            new Language(9, "Bengali"),
            new Language(10, "Bosnian"),
            new Language(11, "Bulgarian"),
            new Language(12, "Catalan"),
            new Language(13, "Cebuano"),
            new Language(14, "Chichewa"),
            new Language(15, "Chinese"),
            new Language(16, "Corsican"),
            new Language(17, "Croatian"),
            new Language(18, "Czech"),
            new Language(19, "Danish"),
            new Language(20, "Dutch"),
            new Language(21, "English"),
            new Language(22, "Esperanto"),
            new Language(23, "Estonian"),
            new Language(24, "Filipino"),
            new Language(25, "Finnish"),
            new Language(26, "French"),
            new Language(27, "Frisian"),
            new Language(28, "Galician"),
            new Language(29, "Georgian"),
            new Language(30, "German"),
            new Language(31, "Greek"),
            new Language(32, "Gujarati"),
            new Language(33, "Haitian Creole"),
            new Language(34, "Hausa"),
            new Language(35, "Hawaiian"),
            new Language(36, "Hebrew"),
            new Language(37, "Hindi"),
            new Language(38, "Hmong"),
            new Language(39, "Hungarian"),
            new Language(40, "Icelandic"),
            new Language(41, "Igbo"),
            new Language(42, "Indonesian"),
            new Language(43, "Irish"),
            new Language(44, "Italian"),
            new Language(45, "Japanese"),
            new Language(46, "Javanese"),
            new Language(47, "Kannada"),
            new Language(48, "Kazakh"),
            new Language(49, "Khmer"),
            new Language(50, "Kinyarwanda"),
            new Language(51, "Korean"),
            new Language(52, "Kurdish"),
            new Language(53, "Kyrgyz"),
            new Language(54, "Lao"),
            new Language(55, "Latin"),
            new Language(56, "Latvian"),
            new Language(57, "Lithuanian"),
            new Language(58, "Luxembourgish"),
            new Language(59, "Macedonian"),
            new Language(60, "Malagasy"),
            new Language(61, "Malay"),
            new Language(62, "Malayalam"),
            new Language(63, "Maltese"),
            new Language(64, "Maori"),
            new Language(65, "Marathi"),
            new Language(66, "Mongolian"),
            new Language(67, "Myanmar"),
            new Language(68, "Nepali"),
            new Language(69, "Norwegian"),
            new Language(70, "Odia"),
            new Language(71, "Pashto"),
            new Language(72, "Persian"),
            new Language(73, "Polish"),
            new Language(74, "Portuguese"),
            new Language(75, "Punjabi"),
            new Language(76, "Romanian"),
            new Language(77, "Russian"),
            new Language(78, "Samoan"),
            new Language(79, "Scots Gaelic"),
            new Language(80, "Serbian"),
            new Language(81, "Sesotho"),
            new Language(82, "Shona"),
            new Language(83, "Sindhi"),
            new Language(84, "Sinhala"),
            new Language(85, "Slovak"),
            new Language(86, "Slovenian"),
            new Language(87, "Somali"),
            new Language(88, "Spanish"),
            new Language(89, "Sundanese"),
            new Language(90, "Swahili"),
            new Language(91, "Swedish"),
            new Language(92, "Tajik"),
            new Language(93, "Tamil"),
            new Language(94, "Tatar"),
            new Language(95, "Telugu"),
            new Language(96, "Thai"),
            new Language(97, "Turkish"),
            new Language(98, "Turkmen"),
            new Language(99, "Ukrainian"),
            new Language(100, "Urdu"),
            new Language(101, "Uyghur"),
            new Language(102, "Uzbek"),
            new Language(103, "Vietnamese"),
            new Language(104, "Welsh"),
            new Language(105, "Xhosa"),
            new Language(106, "Yiddish"),
            new Language(107, "Yoruba"),
            new Language(108, "Zulu")
            );
}